### ISSUE TITLE
Time series plotting

### ISSUE THREAD

**Issue by mindv0rtex** [igiagkiozis/plotly#20]
First of all, thanks for the great library! 

I am trying to plot a temporal sequence, e.g. time series, and I have a vector of `chrono::NaiveDateTime` objects. I can turn them into strings, but I am not sure that this would be enough to make Plotly understand that I want to plot data against dates. Looking through the library code, I see that there is the `AxisType::Date` enum variant, but you don't use it anywhere in the Getting Started guide, so I wanted to clarify the correct way to set this up.

**Comment by igiagkiozis** [comment]
Hi @mindv0rtex,

If you convert your datetimes to strings and use these instead you will get a time-series plot. I know this is not entirely intuitive but this is how the underlying library works (i.e. plotly.js). I have planned adding support for chrono in a future release so that you can just pass a vector of dates and get what you expect.

**Comment by mindv0rtex** [comment]
Is there any specific format that plotly.js needs to recognize datetime objects? My data is defined with the granularity of milliseconds. Should I use the 'yyyy-mm-dd HH:MM:SS.ssssss' format?

Also, is there a way to control the resulting tick format for dates?

Thank you!

**Comment by mfreeborn** [comment]
For posterity, `chrono::datetime::DateTime::to_rfc3339()` will do the conversion in a way that Plotly can interpret.

Tick formatting is available via `Axis::tick_format`, with the JS reference docs [here](https://plotly.com/javascript/reference/layout/xaxis/#layout-xaxis-tickformat).
